package oneapp.incture.workbox.demo.workflow.dto;

import javax.xml.bind.annotation.XmlRootElement;

import oneapp.incture.workbox.demo.adapter_base.dto.BaseDto;
import oneapp.incture.workbox.demo.adapter_base.util.EnOperation;
import oneapp.incture.workbox.demo.adapter_base.util.InvalidInputFault;

@XmlRootElement
public class RuleDto extends BaseDto {

	private String ruleId; // generated by UI

	private String ruleTypeId; // template Id

	private String ruleType; // TBD

	private String custom_key; // custom attr name

	private String condition; // > 20, ='Product'

	private String destination; // target Id

	private String operator; // Not required
	
	private String logic;
	private String value;
	private String attributeName;
	private String validForUsage;

	
	public String getLogic() {
		return logic;
	}

	public void setLogic(String logic) {
		this.logic = logic;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getAttributeName() {
		return attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getRuleId() {
		return ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	public String getRuleTypeId() {
		return ruleTypeId;
	}

	public void setRuleTypeId(String ruleTypeId) {
		this.ruleTypeId = ruleTypeId;
	}

	public String getRuleType() {
		return ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getCustom_key() {
		return custom_key;
	}

	public void setCustom_key(String custom_key) {
		this.custom_key = custom_key;
	}

	public String getCondition() {
		return condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	public String getDestination() {
		return destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Override
	public String toString() {
		return "RuleDto [ruleId=" + ruleId + ", ruleTypeId=" + ruleTypeId + ", ruleType=" + ruleType + ", custom_key="
				+ custom_key + ", condition=" + condition + ", destination=" + destination + ", operator=" + operator
				+ ", logic=" + logic + ", value=" + value + ", attributeName=" + attributeName + "]";
	}

	@Override
	public Boolean getValidForUsage() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void validate(EnOperation enOperation) throws InvalidInputFault {
		// TODO Auto-generated method stub

	}

}
